spring:
  application:
    name: "account-services"
build:
  version: "1.0"
account:
  message: "Welcome to MSEDCL bank account REST API - Uat"
  contactDetails:
    name: "UAT"
    email: "uat@msedcl.in"
  onCallSupport:
    - 1234567890
    - 9876543210
